version: "3.8"

services:
  db:
    container_name: codelogue_db_container
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  backend:
    container_name: codelogue_server_container
    build: ./backend
    command: python manage.py start_server
    volumes:
      - ./backend:/server
    image: library/nginx:alpine
    ports:
      - 5001:5001
    env_file:
      - ./backend/.env
    depends_on:
      - db

#  frontend:
#    container_name: codelogue_client_container
#    build: ./frontend
#    volumes:
#      - ./frontend:/client
#    ports:
#      - 8080:8080


volumes:
  postgres_data: