"""updated migration with tag and snippet_tags tables, modified snippet table

Revision ID: 9c170cfdd51f
Revises: b0dc99658143
Create Date: 2020-07-20 20:41:23.444905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c170cfdd51f'
down_revision = 'b0dc99658143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tagged_snippets',
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('snippet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['snippet_id'], ['snippet.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'snippet_id')
    )
    op.add_column('folder', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.add_column('folder', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'folder', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folder', type_='foreignkey')
    op.drop_column('folder', 'user_id')
    op.drop_column('folder', 'date_created')
    op.drop_table('tagged_snippets')
    op.drop_table('tag')
    # ### end Alembic commands ###
